// Generated by Haxe 3.3.0
package thx.promise;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class TestTryPromise_testTryEitherFailure_38__Fun extends haxe.lang.Function
{
	public TestTryPromise_testTryEitherFailure_38__Fun()
	{
		//line 38 "/shared/promise/test/thx/promise/TestTryPromise.hx"
		super(1, 0);
	}
	
	
	public static thx.promise.TestTryPromise_testTryEitherFailure_38__Fun __hx_current;
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 38 "/shared/promise/test/thx/promise/TestTryPromise.hx"
		java.lang.Object _1 = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((java.lang.Object) (__fn_float1) )) : (((java.lang.Object) (__fn_dyn1) )) );
		//line 38 "/shared/promise/test/thx/promise/TestTryPromise.hx"
		utest.Assert.fail("no reason to get here", new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"thx.promise.TestTryPromise", "TestTryPromise.hx", "testTryEitherFailure"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (38) )) )}));
		//line 38 "/shared/promise/test/thx/promise/TestTryPromise.hx"
		return null;
	}
	
	
}


